name       : gnome-power-manager
version    : '43.0'
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-power-manager/43/gnome-power-manager-43.0.tar.xz : 7daab48bbddb30e9df2aba650cb60d05e667c9f885ace6a0a1e7950e0cbdd32f
homepage   : https://gitlab.gnome.org/GNOME/gnome-power-manager
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : A tool to view power usage
description: |
    A tool for viewing present and historical battery usage and related statistics. Originally part of GNOME Power Manager and remained as a stand alone program after the rest was merged into gnome-settings-daemon.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(upower-glib)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
