name       : gnome-power-manager
version    : 3.26.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-power-manager/3.26/gnome-power-manager-3.26.0.tar.xz : 20aee0b0b4015e7cc6fbabc3cbc4344c07c230fe3d195e90c8ae0dc5d55a2d4e
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : A session daemon for the GNOME desktop environment.
description: |
    GNOME Power Manager is a session daemon for the GNOME desktop environment that makes it easy to manage your laptop or desktop system.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(upower-glib)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
