name       : gnome-power-manager
version    : 3.20.0
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-power-manager/3.20/gnome-power-manager-3.20.0.tar.xz : 159c23a6ed5ffd54324947adb2a32caff6d6e2210f96bdf3961edfcad8058a47
license    : GPL-2.0
component  : desktop.gnome
summary    : A session daemon for the GNOME desktop environment.
description: |
    GNOME Power Manager is a session daemon for the GNOME desktop environment that makes it easy to manage your laptop or desktop system.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(upower-glib)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
