name       : gnome-power-manager
version    : 3.32.0
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-power-manager/3.32/gnome-power-manager-3.32.0.tar.xz : 4f2ca1a756da5061b04042b5cf21008df1267806d76c8e0fb08422c6f8b02e37
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : A session daemon for the GNOME desktop environment.
description: |
    GNOME Power Manager is a session daemon for the GNOME desktop environment that makes it easy to manage your laptop or desktop system.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(upower-glib)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
